
import __ASTRO_IMAGE_IMPORT_bkntr from "./berlin24.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fberlin24%2Fberlin24.md";
import __ASTRO_IMAGE_IMPORT_Z1vDVbC from "vitalik.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fberlin24%2Fberlin24.md";
import __ASTRO_IMAGE_IMPORT_Z1oXXqD from "break.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbreak%2Fbreak.md";
import __ASTRO_IMAGE_IMPORT_ZEhmnm from "redemption.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbreak%2Fbreak.md";
import __ASTRO_IMAGE_IMPORT_pUJQz from "./grand.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsadness%2Fsadness.md";
import __ASTRO_IMAGE_IMPORT_hKUwo from "buildings.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_Z1U5fT6 from "old.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_Z16I7na from "sls.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_Z2qRCPJ from "sp.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_ZYlWoH from "pokemon.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_Z1sl9xB from "stevenchow.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_2vww4R from "siu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_1VGJqm from "hku.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_2tzYGP from "hkusu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_Z1CroTq from "times.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_13Gg1u from "bks.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
import __ASTRO_IMAGE_IMPORT_KmIyk from "hk.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md";
export default new Map([["./berlin24.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fberlin24%2Fberlin24.md", __ASTRO_IMAGE_IMPORT_bkntr], ["vitalik.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fberlin24%2Fberlin24.md", __ASTRO_IMAGE_IMPORT_Z1vDVbC], ["break.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbreak%2Fbreak.md", __ASTRO_IMAGE_IMPORT_Z1oXXqD], ["redemption.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbreak%2Fbreak.md", __ASTRO_IMAGE_IMPORT_ZEhmnm], ["./grand.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsadness%2Fsadness.md", __ASTRO_IMAGE_IMPORT_pUJQz], ["buildings.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_hKUwo], ["old.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_Z1U5fT6], ["sls.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_Z16I7na], ["sp.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_Z2qRCPJ], ["pokemon.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_ZYlWoH], ["stevenchow.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_Z1sl9xB], ["siu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_2vww4R], ["hku.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_1VGJqm], ["hkusu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_2tzYGP], ["times.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_Z1CroTq], ["bks.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_13Gg1u], ["hk.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fstand%2Fstand.md", __ASTRO_IMAGE_IMPORT_KmIyk]]);
		