name: CI
on:
  - push
env:
  CI: true
  TZ: Asia/Hong_Kong

defaults:
  run:
    shell: bash
    working-directory: blog

jobs:
  deploy:
    runs-on: ubuntu-20.04
#    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: yarn install
        run: yarn install
      - name: yarn deploy
        run: yarn run deploy
